[FIX] Add Conditions to page loads

diff --git a/.github/workflows/coverage.yml b/.github/workflows/coverage.yml
--- a/.github/workflows/coverage.yml
+++ b/.github/workflows/coverage.yml
@@ -88,6 +88,17 @@ jobs:
         run: bash ci-generate.sh http://localhost:3000
         working-directory: jwt-pizza-service
 
+      - name: Ensure Database up
+        working-directory: jwt-pizza
+        run: |
+          status_code=$(curl -s -o /dev/null -w "%{http_code}" -X PUT http://localhost:3000/api/auth \
+            -H "Content-Type: application/json" \
+            -d '{"email":"a@jwt.com","password":"'"${{ env.CI_ADMIN_PASSWORD }}"'"}')
+          if [ "$status_code" -ne 200 ]; then
+            echo "Request failed with status $status_code"
+            exit 1
+          fi
+
       - name: Run tests
         run: |
             npm install
